UCLA scl 1.0
# Created : 10/22/2018 17:12:35

NumRows : 383

CoreRow Horizontal
	Coordinate   : 132
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 141
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 150
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 159
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 168
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 177
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 186
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 195
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 204
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 213
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 222
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 231
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 240
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 249
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 258
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 267
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 276
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 285
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 294
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 303
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 312
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 321
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 330
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 339
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 348
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 357
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 366
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 375
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 384
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 393
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 402
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 411
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 420
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 429
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 438
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 447
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 456
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 465
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 474
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 483
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 492
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 501
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 510
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 519
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 528
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 537
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 546
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 555
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 564
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 573
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 582
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 591
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 600
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 609
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 618
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 627
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 636
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 645
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 654
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 663
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 672
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 681
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 690
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 699
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 708
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 717
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 726
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 735
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 744
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 753
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 762
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 771
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 780
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 789
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 798
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 807
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 816
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 825
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 834
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 843
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 852
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 861
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 870
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 879
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 888
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 897
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 906
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 915
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 924
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 933
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 942
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 951
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 960
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 969
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 978
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 987
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 996
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1005
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1014
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1023
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1032
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1041
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1050
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1059
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1068
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1077
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1086
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1095
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1104
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1113
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1122
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1131
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1140
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1149
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1158
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1167
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1176
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1185
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1194
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1203
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1212
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1221
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1230
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1239
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1248
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1257
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1266
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1275
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1284
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1293
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1302
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1311
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1320
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1329
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1338
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1347
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1356
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1365
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1374
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1383
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1392
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1401
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1410
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1419
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1428
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1437
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1446
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1455
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1464
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1473
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1482
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1491
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1500
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1509
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1518
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1527
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1536
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1545
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1554
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1563
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1572
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1581
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1590
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1599
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1608
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1617
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1626
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1635
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1644
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1653
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1662
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1671
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1680
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1689
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1698
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1707
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1716
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1725
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1734
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1743
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1752
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1761
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1770
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1779
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1788
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1797
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1806
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1815
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1824
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1833
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1842
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1851
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1860
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1869
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1878
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1887
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1896
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1905
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1914
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1923
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1932
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1941
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1950
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1959
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1968
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1977
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1986
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 1995
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2004
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2013
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2022
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2031
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2040
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2049
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2058
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2067
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2076
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2085
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2094
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2103
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2112
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2121
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2130
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2139
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2148
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2157
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2166
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2175
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2184
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2193
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2202
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2211
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2220
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2229
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2238
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2247
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2256
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2265
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2274
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2283
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2292
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2301
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2310
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2319
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2328
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2337
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2346
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2355
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2364
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2373
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2382
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2391
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2400
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2409
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2418
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2427
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2436
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2445
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2454
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2463
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2472
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2481
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2490
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2499
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2508
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2517
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2526
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2535
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2544
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2553
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2562
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2571
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2580
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2589
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2598
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2607
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2616
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2625
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2634
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2643
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2652
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2661
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2670
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2679
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2688
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2697
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2706
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2715
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2724
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2733
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2742
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2751
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2760
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2769
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2778
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2787
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2796
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2805
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2814
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2823
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2832
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2841
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2850
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2859
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2868
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2877
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2886
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2895
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2904
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2913
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2922
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2931
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2940
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2949
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2958
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2967
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2976
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2985
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 2994
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3003
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3012
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3021
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3030
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3039
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3048
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3057
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3066
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3075
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3084
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3093
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3102
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3111
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3120
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3129
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3138
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3147
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3156
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3165
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3174
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3183
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3192
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3201
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3210
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3219
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3228
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3237
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3246
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3255
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3264
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3273
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3282
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3291
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3300
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3309
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3318
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3327
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3336
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3345
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3354
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3363
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3372
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3381
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3390
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3399
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3408
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3417
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3426
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3435
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3444
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3453
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3462
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3471
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3480
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3489
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3498
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3507
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3516
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3525
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3534
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3543
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3552
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3561
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
CoreRow Horizontal
	Coordinate   : 3570
	Height       : 9
	Sitewidth    : 1
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 125	NumSites : 4692
End
